/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/auth-otp`; params?: Router.UnknownInputParams; } | { pathname: `/debug-supabase`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/landing`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/aquascape` | `/aquascape`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/catalog` | `/catalog`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/community` | `/community`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mytank` | `/mytank`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/create-tank`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/goals`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/paywall`; params?: Router.UnknownInputParams; } | { pathname: `/profile/[userId]`, params: Router.UnknownInputParams & { userId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/auth-otp`; params?: Router.UnknownOutputParams; } | { pathname: `/debug-supabase`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/landing`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/aquascape` | `/aquascape`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/catalog` | `/catalog`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/community` | `/community`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/mytank` | `/mytank`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/create-tank`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/goals`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/paywall`; params?: Router.UnknownOutputParams; } | { pathname: `/profile/[userId]`, params: Router.UnknownOutputParams & { userId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/auth-otp${`?${string}` | `#${string}` | ''}` | `/debug-supabase${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/landing${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/aquascape${`?${string}` | `#${string}` | ''}` | `/aquascape${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/catalog${`?${string}` | `#${string}` | ''}` | `/catalog${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/community${`?${string}` | `#${string}` | ''}` | `/community${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/mytank${`?${string}` | `#${string}` | ''}` | `/mytank${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/onboarding/create-tank${`?${string}` | `#${string}` | ''}` | `/onboarding/goals${`?${string}` | `#${string}` | ''}` | `/onboarding${`?${string}` | `#${string}` | ''}` | `/onboarding/paywall${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/auth-otp`; params?: Router.UnknownInputParams; } | { pathname: `/debug-supabase`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/landing`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/aquascape` | `/aquascape`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/catalog` | `/catalog`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/community` | `/community`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mytank` | `/mytank`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/create-tank`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/goals`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/paywall`; params?: Router.UnknownInputParams; } | `/profile/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/profile/[userId]`, params: Router.UnknownInputParams & { userId: string | number; } };
    }
  }
}
